### PR TITLE
[DLFL23] 14-truck_backer_upper.ipynb - Fix oudated matplotlib API usage 

### PR DESCRIPTION
**Pull request by dqian3**
Was trying to get the truck backer upper working as shown in the NYU Deep Learning class, but rather than downgrade jupyter and matplotlib, I figured out what needed to be changed to make the the notebook work with the latest version.

Tested with a fresh conda install, but haven't tried the other notebooks.

Summary of changes:

- Remove old positional argument in `matplotlib.patches.Rectangle`
- Replace `pylab` imports with python `random` and `math` modules.
- `truck_backer-upper` => `truck_backer_upper`
- Add ipympl and use `%matplotlib notebook`

### CODE REVIEW

**Comment by smith-kyle** [comment]
Just a heads up, you can review notebook changes like this using [GitNotebooks](https://gitnotebooks.com).

e.g. this pull request [https://gitnotebooks.com/Atcold/NYU-DLSP20/pull/846](https://gitnotebooks.com/Atcold/NYU-DLSP20/pull/846)

It allows inline comments on code and markdown, and it's free for public repos so I thought I'd share..

**Comment by Atcold** [comment]
@smith-kyle, how is it any different from [ReviewNB](https://www.reviewnb.com/)?

**Comment by smith-kyle** [comment]
@Atcold Pretty similar but it's a bit more performant, supports multi-line comments, and code comments appear inline like GitHub

**Comment by Atcold** [comment]
@smith-kyle, I'm not sure why you're telling me this on this PR, though.

**Comment by Atcold** [comment]
This is great, @dqian3! I should have updated this code a while ago.
Moreover, a student just completed the notebook.
I'll push that soon here, as soon as it's polished enough.

**Comment by dqian3** [comment]
@Atcold thanks for merging this in! Would be very curious to see what ended up needing to change to finish the notebook, I remember I took a stab at it a while ago but got caught up on some issues with the simulation network.

**Pull request merged**
